spring:
  jwt:
    secret: "secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey"
  jpa:
    hibernate:
        ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      springframework:
        data:
          redis:
            core: DEBUG
            connection: TRACE
