spring:
  application:
    name: search-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: false
