spring:
  application:
    name: search-service

  datasource:
    url: jdbc:mysql://localhost:3306/playus
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      read:
        enabled: true
        uri: mongodb://localhost:27017/read_db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  health:
    redis:
      enabled: false
