server:
  forward-headers-strategy: framework  # ALB HTTPS 헤더 인식

spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # HikariCP 설정 추가
    hikari:
      connection-timeout: 20000         # 연결 타임아웃 20초
      idle-timeout: 300000              # 유휴 연결 타임아웃 5분
      max-lifetime: 900000              # 최대 연결 수명 15분
      maximum-pool-size: 10             # 최대 연결 수
      minimum-idle: 2                   # 최소 유휴 연결 수
      validation-timeout: 5000          # 연결 검증 타임아웃 5초
      leak-detection-threshold: 60000   # 연결 누수 감지 60초

  data:
    mongodb:
      read:
        uri: ${SPRING_DATA_MONGODB_READ_URI}

    redis:
      cluster:
        nodes: ${REDIS_CLUSTER_NODES}
      timeout: 5s
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false  # 성능 개선을 위해 추가
    properties:
      hibernate.format_sql:    true
      hibernate.show_sql:      true
      hibernate.jdbc.time_zone: Asia/Seoul
      # 배치 처리 성능 개선
      hibernate.jdbc.batch_size: 20
      hibernate.order_inserts: true
      hibernate.order_updates: true
      # 연결 관련 개선
      hibernate.connection.provider_disables_autocommit: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - phone_number
              - gender
              - birthday
              - birthyear
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - mobile
              - gender
              - birthyear
              - birthday
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  jwt:
    secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      access-key: ${STORAGE_ACCESS_KEY}
      secret-key: ${STORAGE_SECRET_KEY}
    s3:
      bucket : ${BUCKET_NAME}
      endpoint : ${BUCKET_ENDPOINT}

management:
  health:
    redis:
      enabled: false

  endpoints:
    web:
      exposure:
        include:
          - health           # 애플리케이션 상태 확인
          - info             # 애플리케이션 정보
          - prometheus       # 메트릭 데이터 노출

  endpoint:
    health:
      show-details: never

app:
  frontend:
    success-redirect-uri: ${FRONT_SUCCESS_REDIRECT_URI}
    success-redirect-uri2: ${FRONT_SUCCESS_REDIRECT_URI2}
    fail-redirect-uri: ${FRONT_FAIL_REDIRECT_URI}

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 10s
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 0s
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
    instances:
      circuit:
        base-config: default

sentry:
  dsn: ${SENTRY_REPOSITORY_DSN}
  environment: ${SENTRY_ENVIRONMENT}
  servername: ${SENTRY_SERVERNAME}
  repository-uri: ${SENTRY_REPOSITORY_URI}

logging:
  config: classpath:logback-spring.xml

slack:
  webhook-url: ${SLACK_WEBHOOK_URL}

feign:
  match:
    url: ${FEIGN_MATCH_URL}

  community:
    url: ${FEIGN_COMMUNITY_URL}

cookie:
  secure: true
  sameSite: None
