spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      read:
        uri: ${SPRING_DATA_MONGODB_READ_URI}

    redis:
      host: localhost
      port: 6379

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - phone_number
              - gender
              - birthday
              - birthyear
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - mobile
              - gender
              - birthyear
              - birthday
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

  jwt:
    secret: ${JWT_SECRET}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


management:
  health:
    redis:
      enabled: false

  endpoints:
    web:
      exposure:
        include:
          - health           # 애플리케이션 상태 확인
          - info             # 애플리케이션 정보
          - prometheus       # 메트릭 데이터 노출

  endpoint:
    health:
      show-details: always

app:
  frontend:
    redirect-uri: http://localhost:3000/PlayUs-FE#/choice-team

sentry:
  dsn: ${SENTRY_REPOSITORY_DSN}
  environment: ${SENTRY_ENVIRONMENT}
  servername: ${SENTRY_SERVERNAME}
  repository-uri: ${SENTRY_REPOSITORY_URI}

logging:
  config: classpath:logback-spring.xml

slack:
  webhook-url: ${SLACK_WEBHOOK_URL}
