server:
  forward-headers-strategy: framework  # ALB HTTPS 헤더 인식

spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}?useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&socketTimeout=60000&connectTimeout=60000
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # OCI 프록시 환경 최적화 HikariCP 설정
    hikari:
      connection-timeout: 60000          # OCI 네트워크 지연 고려 60초
      idle-timeout: 60000                # OCI 프록시가 빨리 끊으므로 1분
      max-lifetime: 180000               # OCI 프록시 정책 고려 3분
      keepalive-time: 30000
      maximum-pool-size: 5               # 작은 풀 크기 (OCI 동시 연결 제한)
      minimum-idle: 1                    # 최소한만 유지
      validation-timeout: 10000          # 네트워크 지연 고려 10초
      leak-detection-threshold: 30000    # 30초로 단축
      connection-test-query: "SELECT 1"  # 연결 검증 쿼리
      auto-commit: false


  data:
    mongodb:
      read:
        uri: ${SPRING_DATA_MONGODB_READ_URI}&connectTimeoutMS=30000&socketTimeoutMS=30000&serverSelectionTimeoutMS=10000&maxIdleTimeMS=60000

    redis:
      cluster:
        nodes: ${REDIS_CLUSTER_NODES}
      timeout: 5s
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
      repositories:
        enabled: false

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false  # 성능 개선을 위해 추가
    properties:
      hibernate.format_sql:    true
      hibernate.show_sql:      true
      hibernate.jdbc.time_zone: Asia/Seoul

      # OCI 환경에서 안정성 우선 설정
      hibernate.jdbc.batch_size: 1     # 배치 비활성화 (안정성 우선)
      hibernate.order_inserts: false   # OCI 환경에서 순서 보장 비활성화
      hibernate.order_updates: false

      # OCI 프록시 연결 관리
      hibernate.connection.acquisition_timeout: 60000
      hibernate.connection.validation_timeout: 10000

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - phone_number
              - gender
              - birthday
              - birthyear
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - mobile
              - gender
              - birthyear
              - birthday
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  jwt:
    secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      access-key: ${STORAGE_ACCESS_KEY}
      secret-key: ${STORAGE_SECRET_KEY}
    s3:
      bucket : ${BUCKET_NAME}
      endpoint : ${BUCKET_ENDPOINT}

management:
  health:
    redis:
      enabled: false

  endpoints:
    web:
      exposure:
        include:
          - health           # 애플리케이션 상태 확인
          - info             # 애플리케이션 정보
          - prometheus       # 메트릭 데이터 노출

  endpoint:
    health:
      show-details: never

app:
  frontend:
    success-redirect-uri: ${FRONT_SUCCESS_REDIRECT_URI}
    success-redirect-uri2: ${FRONT_SUCCESS_REDIRECT_URI2}
    fail-redirect-uri: ${FRONT_FAIL_REDIRECT_URI}

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 60
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 15s
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 0s
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 15s
    instances:
      circuit:
        base-config: default

  # OCI 환경 Retry 설정 추가
  retry:
    configs:
      default:
        max-attempts: 5    # OCI 환경에서 재시도 증가
        wait-duration: 2s
        retry-exceptions:
          - java.sql.SQLException
          - com.mysql.cj.jdbc.exceptions.CommunicationsException
          - java.net.SocketTimeoutException
    instances:
      database:
        base-config: default

sentry:
  dsn: ${SENTRY_REPOSITORY_DSN}
  environment: ${SENTRY_ENVIRONMENT}
  servername: ${SENTRY_SERVERNAME}
  repository-uri: ${SENTRY_REPOSITORY_URI}

logging:
  config: classpath:logback-spring.xml

slack:
  webhook-url: ${SLACK_WEBHOOK_URL}

feign:
  match:
    url: ${FEIGN_MATCH_URL}

  community:
    url: ${FEIGN_COMMUNITY_URL}

cookie:
  secure: true
  sameSite: None
