spring:
  application:
    name: search-service

  datasource:
    url: jdbc:mysql://localhost:3306/playus
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      read:
        uri: mongodb://localhost:27017/read_db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - phone_number
              - gender
              - age_range
              - birthday
              - birthyear
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jwt:
    secret: cGxheXVza2FrYW9uYXZlcm9hdXRobG9naW5qd3Q=

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


management:
  health:
    redis:
      enabled: false
