spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      read:
        uri: ${SPRING_DATA_MONGODB_READ_URI}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql:    true
      hibernate.show_sql:      true
      hibernate.jdbc.time_zone: Asia/Seoul

aws:
  s3:
    access-key:  ${AWS_S3_ACCESS_KEY}
    secret-key:  ${AWS_S3_SECRET_KEY}
    bucket-name: ${AWS_S3_BUCKET_NAME}
    endpoint:    ${AWS_S3_ENDPOINT}
