name: 'User Service Github-Jira 이슈 생성'
description: '이슈 생성 폼'
title : '이슈를 작성해주세요'
labels : []
assignees : ['민우', '채민', '현우']

body:
  - type : input
    id : parentKey
    attributes:
      label: '상위 작업 Ticket Number'
      description: '상위 직업 (Story) 의 Ticket Number를 기입해주세요, 노션에서 확인 가능'
      value: CS-00
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: '이슈 내용 (Description)'
      description: '이슈 대해 간략히 요약해주세요'
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: '담당자 이름'
      description: '이슈를 맡는 담당자에 대해 이야기해주세요.'
  #    validations:
  #      required: true

  - type : textarea
    id : details
    attributes:
      label : '상세 내용 (Details)'
      description: '이슈 대해 자세히 설명해주세요'
      value: |
        - About Details

  - type: textarea
    id: tasks
    attributes:
      label: '체크리스트 (Tasks)'
      description: '해당 이슈 대해 필요한 작업목록을 작성해주세요'
      value: |
        - [ ] Tasks1
        - [ ] Tasks2

  - type : textarea
    id : references
    attributes:
      label : '참조 (References)'
      description: '해당 이슈 관련된 레퍼런스 참조해주세요'
      value : |
        - Reference1