name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:  # 수동 실행 허용

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean bootJar

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker image tags
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          BUILD_VERSION=${{ github.run_number }}-${SHORT_SHA}

          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "BASE_TAG=latest" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "develop" ]]; then
            echo "BASE_TAG=dev" >> $GITHUB_ENV
          fi

          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/playus-user-service:${{ env.BASE_TAG }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/playus-user-service:${{ env.BUILD_VERSION }} .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/playus-user-service:${{ env.BASE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/playus-user-service:${{ env.BUILD_VERSION }}

      - name: Update patch-image.yaml
        if: success()

        run: |
          git clone https://x-access-token:${{ secrets.K8S_REPO_TOKEN }}@github.com/KEA-ChunSam/PlayUs-k8s.git

          BRANCH_NAME=${GITHUB_REF##*/}
          if [[ "$BRANCH_NAME" == "main" ]]; then 
            echo "Skipping main branch update (prod) for now"
          elif [[ "$BRANCH_NAME" == "develop" ]]; then
            sed -i "/name: user-service/{n;s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/playus-user-service:${{ env.BUILD_VERSION }}|}" PlayUs-k8s/overlays/dev/patch-image.yaml
          fi

          cd PlayUs-k8s
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Update user-service image to ${{ env.BUILD_VERSION }} on $BRANCH_NAME"
            git push https://x-access-token:${{ secrets.K8S_REPO_TOKEN }}@github.com/KEA-ChunSam/PlayUs-k8s.git
          else
            echo "커밋할 변경사항이 없습니다"
          fi
